CodiPlatform/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()


import CodiPlatform.registration.views
import CodiPlatform.general.views
import CodiPlatform.codi.views
import CodiPlatform.setting.views
import CodiPlatform.message.views
import CodiPlatform.search.views

from CodiPlatform import settings

urlpatterns = patterns('',
                            
    # Examples:
    #url(r'^$', 'CodiPlatform.views.home', name='home'),
    # url(r'^CodiPlatform/', include('CodiPlatform.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^home/(\w+(.\w+)*)/$', CodiPlatform.home.views.home),
    url(r'^home/$', CodiPlatform.general.views.home),
    #url(r'^home/dashboard$', CodiPlatform.home.views.dashboard),
    #url(r'^home/inbox', CodiPlatform.home.views.inbox),
    #url(r'^home/profile', CodiPlatform.home.views.profile),

    url(r'^signup/$', CodiPlatform.registration.views.signup),
    url(r'^signup/thanks/$', CodiPlatform.registration.views.signup_thanks),
    url(r'^login/$', CodiPlatform.registration.views.custom_login),
    url(r'^logout/$', CodiPlatform.registration.views.custom_logout),
    url(r'^$', CodiPlatform.general.views.main),
    url(r'^info/how_it_works/$', CodiPlatform.general.views.how_it_works),
    url(r'^codi/([a-z0-9A-Z]+(\.[a-z0-9A-Z]+)*)/$', CodiPlatform.codi.views.codi),
    url(r'^codi/([a-z0-9A-Z]+(\.[a-z0-9A-Z]+)*)/gallery/(.*)$', CodiPlatform.codi.views.codi_gallery),
    url(r'^codi/([a-z0-9A-Z]+(\.[a-z0-9A-Z]+)*)/info/$', CodiPlatform.codi.views.codi_info),
    url(r'^codi/([a-z0-9A-Z]+(\.[a-z0-9A-Z]+)*)/wall/$', CodiPlatform.codi.views.codi_wall),
    url(r'^codi/([a-z0-9A-Z]+(\.[a-z0-9A-Z]+)*)/schedule/$', CodiPlatform.codi.views.codi_schedule),

    url(r'^codi/([a-z0-9A-Z]+(\.[a-z0-9A-Z]+)*)/consulting/$', CodiPlatform.codi.views.codi_consulting),
    url(r'^codi/([a-z0-9A-Z]+(\.[a-z0-9A-Z]+)*)/review/$', CodiPlatform.codi.views.codi_review),


    url(r'^codi/$', CodiPlatform.codi.views.my_codi),
    
    url(r'^showcase/$', CodiPlatform.codi.views.showcase),
    url(r'^showcase/([1-9]+)/([1-9]+)/$', CodiPlatform.codi.views.showcase_episode),
    url(r'^showcase/([1-9]+)/([1-9]+)/([1-9]+)/$', CodiPlatform.codi.views.showcase_part),

    
    
    url(r'^codiscoach/$', CodiPlatform.codi.views.codiscoach),
    url(r'^tryout/$', CodiPlatform.codi.views.tryout),
    url(r'^setting/account/$', CodiPlatform.setting.views.account_setting),
    url(r'^setting/codi/$', CodiPlatform.setting.views.codi_setting_push_album),
    url(r'^setting/codi/push_album/$', CodiPlatform.setting.views.codi_setting_push_album),
    url(r'^message/$', CodiPlatform.message.views.message),
    url(r'^search/$', CodiPlatform.search.views.codi_search),
    url(r'^album/(.+)/$', CodiPlatform.general.views.album),
    url(r'^post/(.+)/$', CodiPlatform.general.views.post),


    
    
    #redirect the result of 'login' view
    #url(r'^accounts/profile/$', CodiPlatform.home.views.home),
   # url(r'^accounts/login/$', login),
)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

CodiPlatform/codi/models.py
from django.db import models
'''
# Create your models here.
class Theme(models.Model):
    title = models.CharField(max_length = 100)
     

'''

CodiPlatform/general/models.py
from django.db import models
import os, os.path
from binascii import hexlify
from CodiPlatform.registration.models import CustomUser
#from CodiPlatform.settings import basedir
import datetime
def _createId():
    return hexlify(os.urandom(16))

def _createPath(instance, filename):
    return os.path.join('photos', instance.photo_id)

'''
# Create your models here.
class User(models.Model):
    #user_id = models.CharField(max_length = 20, primary_key = True)
    first_name = models.CharField(max_length = 20, verbose_name = 'First Name:')#, min_length = 2)
    last_name = models.CharField(max_length = 20, verbose_name = 'Last Name:')#, min_length = 2)
    #profile_photo = models.ImageField(upload_to=os.path.join(os.path.dirname(__file__), 'photo/codi/%d'%codi_id))
    #email = models.CharField(verbose_name = 'Your Email:')
    
    def __unicode__(self):
        return '%s %s' %(self.first_name, self.last_name)
    '''
class TitlePhoto(models.Model):
    photo_id = models.CharField(max_length=32, primary_key=True, default=_createId)
    #title = models.CharField(max_length=30)#, min_length = 4)
    image = models.ImageField(upload_to = _createPath)

class Theme(models.Model):
    season = models.PositiveIntegerField()
    episode = models.PositiveIntegerField()
    part = models.PositiveIntegerField()
    title = models.CharField(max_length = 50)

class Vote(models.Model):
    #season = models.PositiveIntegerField()
    #episode = models.PositiveIntegerField()
    #part = models.PositiveIntegerField()
    theme = models.ForeignKey(Theme)
    owner = models.ForeignKey(CustomUser)
    
#class ThemeBattle(models.Model):
#    album1 = models.m

class Album(models.Model):
    album_id = models.CharField(max_length=32, primary_key=True, default=_createId)
    title = models.CharField(max_length=30)
    title_photo = models.OneToOneField(TitlePhoto)
    owner = models.ForeignKey(CustomUser)
    message = models.TextField(max_length=500)
    time_created = models.DateTimeField(auto_now_add = True, default=datetime.date.today())
    time_modified = models.DateTimeField(auto_now = True, default=datetime.date.today())
    category = models.CharField(max_length=40)
    unique_visit = models.PositiveIntegerField(default = 1)
    all_visit = models.PositiveIntegerField(default = 1)
    
    # if category is theme
    theme = models.ForeignKey(Theme, blank = True, null = True)
    time_voted = models.DateTimeField(default=datetime.date.today())
    elo = models.PositiveIntegerField(default = 1500)

    def __unicode__(self):
        return self.title

class Photo(models.Model):
    photo_id = models.CharField(max_length=32, primary_key=True, default=_createId)
    #title = models.CharField(max_length=30)#, min_length = 4)
    image = models.ImageField(upload_to = _createPath)
    album = models.ForeignKey(Album)
    position = models.CharField(max_length=1)
    
    def __unicode__(self):
        return '%s #%s' %(self.album.title, self.position)

class Post(models.Model):
    post_id = models.CharField(max_length=32, primary_key=True, default=_createId)
    owner = models.ForeignKey(CustomUser)
    message = models.TextField(max_length=500)
    time_created = models.DateTimeField(auto_now_add = True, default=datetime.date.today())
    time_modified = models.DateTimeField(auto_now = True, default=datetime.date.today())
    unique_visit = models.PositiveIntegerField(default = 1)
    all_visit = models.PositiveIntegerField(default = 1)

    def __unicode__(self):
        return self.owner.user.get_full_name()

class Comment(models.Model):
    comment_id = models.CharField(max_length=32, primary_key=True, default=_createId)
    #title = models.CharField(max_length=30)#, min_length = 4)
    owner = models.ForeignKey(CustomUser)

    message = models.TextField(max_length=100)
    time_created = models.DateTimeField(auto_now_add = True, default=datetime.date.today())
    time_modified = models.DateTimeField(auto_now = True, default=datetime.date.today())

    post = models.ForeignKey(Post)
    
    def __unicode__(self):
        return '%s' %(self.post.owner)

    

CodiPlatform/message/models.py
from django.db import models

# Create your models here.

CodiPlatform/search/models.py
from django.db import models

# Create your models here.

CodiPlatform/setting/forms.py
from django.forms.fields import DateField, ChoiceField, MultipleChoiceField
from django.forms.widgets import Select, CheckboxSelectMultiple
from CodiPlatform.general.models import Theme, Album

'''
Created on Dec 24, 2011

@author: wonjohnchoi
'''
from CodiPlatform.settings import SEASON, EPISODE
from django import forms

class AlbumForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(AlbumForm, self).__init__(*args, **kwargs)

    title = forms.CharField(max_length = 50)
    title_photo = forms.ImageField(max_length = 500)
    photo1  = forms.ImageField(max_length = 500, required=False)
    photo2  = forms.ImageField(max_length = 500, required=False)
    photo3  = forms.ImageField(max_length = 500, required=False)
    photo4  = forms.ImageField(max_length = 500, required=False)
    photo5  = forms.ImageField(max_length = 500, required=False)
    photo6  = forms.ImageField(max_length = 500, required=False)
    message = forms.CharField(widget=forms.Textarea)
    category = ChoiceField(widget=Select,
        choices=(('sample', 'Sample'), ('review', 'Review'),
        ('market', 'Make a coordi for clients')) +
        tuple(('theme|%d|%d|%d' % (SEASON, EPISODE, theme.part), 'Theme Battle - %s' %theme.title) for theme in Theme.objects.filter(season=SEASON, episode=EPISODE)))
    
    #def __init__(self, user, *args, **kwargs):
    #    super(AlbumForm, self).__init__(*args, **kwargs)
        
    #    if not user.is_authenticated():
    #        self.fields['captcha'] = AlbumForm()

    
    def clean_category(self):
        category =  self.data['category']
        if category.startswith('theme'):
            data = category.split('|')
            print data
            if data[1] != unicode(SEASON) or data[2] != unicode(EPISODE) or len(data) != 4:
                raise forms.ValidationError('SEASON or EPISODE do not match.')
            
            try:
                Theme.objects.get(season = data[1], episode = data[2], part = data[3])
            except Theme.DoesNotExist:
                raise forms.ValidationError('PART do not match.')
            try:
                Album.objects.get(owner__user = self.request.user, theme__season = data[1], theme__episode = data[2])
                raise forms.ValidationError('You already submitted an album for season %s - episode %s.' %(data[1], data[2]))
            except Album.DoesNotExist:
                pass
            return data
        return category
    def clean(self,*args, **kwargs):
        self.clean_category()
        #self.clean_title()
        return super(AlbumForm, self).clean(*args, **kwargs)
    

CodiPlatform/message/views.py
# Create your views here.
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.contrib.auth.models import User
from CodiPlatform.registration.models import CustomUser
from CodiPlatform.registration.models import Message
from django.db.models import Q

@login_required
def message(request):
    #custom_user = CustomUser.objects.get(user = request.user)
    user = request.user
    
    other_ids = set()
    for msg in Message.objects.filter(sender_id = user.username):
        other_ids.add(msg.recipient_id)
    for msg in Message.objects.filter(recipient_id = user.username):
        other_ids.add(msg.sender_id)
    print other_ids
    
    other_users = []
    for user_id in other_ids:
        print 'other_user:', user_id
        if user_id != 'admin':
            other_users.append(User.objects.get(username = user_id))
    other_users.sort(key = lambda other: other.first_name)
    print other_users
    # others = CustomUser.objects.filter(other = request.user).order_by('first_name', 'last_name')
    context = {'others' : other_users, 'messages' : None}
    
    if request.method != 'GET' or 'sm' not in request.GET or request.GET['sm'] == '__all':
        target = None
    else:
        try:
            target = CustomUser.objects.get(user__username = request.GET['sm']).user
            target_name = target.username
            print 'target:', target_name
            context['messages'] = Message.objects.all().filter((Q(sender_id = user.username) & Q(recipient_id = target_name))
                                                         | (Q(recipient_id = user.username) & Q(sender_id = target_name))).order_by('-time')
        except CustomUser.DoesNotExist:
            target = None
            print 'no such target!'
    #print custom_user.user.username
    #print Message.objects.filter(sender = custom_user)
    #select all
    if target is None:
        context['messages'] = Message.objects.all().filter(Q(sender_id = user.username) | Q(recipient_id = user.username)).order_by('-time')
            
    return render_to_response('message.html', context, context_instance = RequestContext(request))

CodiPlatform/search/views.py
# Create your views here.
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.contrib.auth.models import User
from CodiPlatform.registration.models import CustomUser
from CodiPlatform.registration.models import Message
from django.db.models import Q

def codi_search(request):
    if request.method == 'GET' and 'arg' in request.GET:
        arg = request.GET['arg']
        results = CustomUser.objects.exclude(codi = None).filter(Q(user__first_name__istartswith = arg) | Q(user__last_name__istartswith = arg) | Q(user__username__istartswith = arg))
        return render_to_response('search.html', {'results' : results}, context_instance = RequestContext(request))
    else:
        return HttpResponseRedirect('/home/')

CodiPlatform/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Codi&Coach</title>
	    
	<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/base.css" />
</head>

<body>
	<span id="topbar"> 	
		<table width="100%">
		<tr valign="top" align="center">
		
		<!--
		<td width = 16>	<a href="/"><img src="{{ STATIC_URL }}logo" width="16" height="16" /></a></td>
		-->
		<td><a href="/">Co&Co</a></td>
		<td><a href="/info/how_it_works/">How It Works</a></td>
		<!--<td><a href="/codiscoach/">Codi's Coach</a></td>
		
		<td><a href="/tryout/">Try-Out</a></td>-->
      <td><a href="/showcase/">Showcase</a></td>
		
		
	    {% if user.is_authenticated %}
		<td><a href="/message/">Messages</a></td>   
		{% endif %}
		
		<td><form name="input" action="/search/" method="get">
		<input type="text" name="arg" />
		<!--<input type="submit" value="Submit" />--></form></td>
		
		<!--
	    {% if user.is_authenticated %}	 
		<td><a href="/home/">{{user.get_full_name}}</a></td>
			{% if custom_user.codi %}
			<td><a href="/codi/{{user.username}}">My Codi</a></td>
			<td><a href="/setting/codi/">Codi Setting</a></td>	
			{% endif %}
		<td><a href="/setting/account/">Account Setting</a></td>
		<td><a href="/logout/">Logout</a></td>
	    {% else %}
		<td><a href="/login/">Login</a></td>
		{% endif %}-->
		
	    {% if user.is_authenticated %}	 	
		<td onMouseOver="document.all.dropdown.style.display = 'block'">
		<a href="/home/">{{user.username}}</a></td>
	    {% else %}
		<td><a href="/login/">Login</a></td>
		{% endif %}
	
		</tr>
		</table>
	  		
	</span>
	
    {% if user.is_authenticated %}
        <table id="dropdown">
            <tr><td>
            <a href="/home/">Home</a>
            </td></tr>
        {% if custom_user.codi %}
            <tr><td>
            <a href="/codi/{{user.username}}">My Coordi</a>
            </td></tr>
    
            <tr><td>
            <a href="/setting/codi/">Coordi Setting</a></td>
            </td></tr>
        {% endif %}

            <tr><td>
            <a href="/setting/account/">Account Setting</a>
            </td></tr>

            <tr><td>
            <a href="/logout/">Logout</a>
            </td></tr>
        </table>
    {% endif %}
    
	{% block content %} {% endblock %}
    {% block footer %}
    <!--
	<div id="footer">
	<hr>
	    <a href="/info/how_it_works">How It Works</a> | 
	    <br/>
		<div id="copyright">&copy; Coach&Codi</div>
	  	<br/>
	</div>
	-->
    {% endblock %}
    
</body>
</html>

CodiPlatform/templates/codi_notexist.html
{% extends "nosidebar.html" %}

{% block main %}
<h1>The page you requested was not found.</h1>
You may have clicked an expired link or mistyped the address.
Some web addresses are case sensitive.

<li><a href="/home/">Return home</a></li>
<li><a href="javascript:javascript:history.go(-1)">Go back to the previous page</a></li>
{% endblock %}

CodiPlatform/templates/codi_schedule.html
{% extends "codi_sidebar.html" %}

{% block sidemain %}
<h1> Schedule </h1>

{% endblock %}

CodiPlatform/templates/codiscoach.html
{% extends "nosidebar.html" %}

{% block main %}
<h1> Codi's Coach </h1>
{% endblock %}

CodiPlatform/templates/how_it_works.html
{% extends "nosidebar.html" %}

{% block main %}
<h1>How It works</h1>

Tell me how it works!
{% endblock %}

CodiPlatform/templates/http404.html
{% extends "nosidebar.html" %}

{% block main %}
<h1>The page you requested was not found.</h1>
You may have clicked an expired link or mistyped the address.
Some web addresses are case sensitive.

<li><a href="/home/">Return home</a></li>
<li><a href="javascript:javascript:history.go(-1)">Go back to the previous page</a></li>
{% endblock %}

CodiPlatform/templates/nosidebar.html
{% extends "base.html" %}
{% block content %}

<div id="main" onMouseOver="document.all.dropdown.style.display = 'none'"> 
    {% block main %}{% endblock %}
</div>
{% endblock %}

CodiPlatform/templates/setting_account.html
{% extends "nosidebar.html" %}

{% block main %}
<h1>Account Setting</h1>

{% endblock %}

CodiPlatform/templates/setting_codi_push_album.html
{% extends "setting_codi_sidebar.html" %}


{% block sidemain %}
	<h1>Add Album</h1>

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.            
        </p>
    {% endif %}
	{% if uploaded %}
	New album is successfully uploaded:
	Click <a href="/album/{{uploaded.album_id}}">{{uploaded.title}}</a>
	{% endif %}
	
    <form action="" enctype="multipart/form-data" method="post">{% csrf_token %}

    
        <div class="field">
            {{ form.title.errors }}
            <label for="id_title">Title:</label>
            {{ form.title }}
        </div>
        <div class="field">
            {{ form.category.errors }}
            <label for="id_category">Category:</label>
            {{ form.category }}
        </div>
        
        <div class="field">
            {{ form.title_photo.errors }}
            <label for="id_title_photo">Title Photo:</label>
            {{ form.title_photo }}
        </div>
        
       	
        <div class="field">
            {{ form.photo1.errors }}
            <label for="id_photo1">Photo1:</label>
            {{ form.photo1 }}
        </div>
        <div class="field">
            {{ form.photo2.errors }}
            <label for="id_photo2">Photo2:</label>
            {{ form.photo2 }}
        </div>
        
        <div class="field">
            {{ form.photo3.errors }}
            <label for="id_photo3">Photo3:</label>
            {{ form.photo3 }}
        </div>
        <div class="field">
            {{ form.photo4.errors }}
            <label for="id_photo4">Photo4:</label>
            {{ form.photo4 }}
        </div>
        <div class="field">
            {{ form.photo5.errors }}
            <label for="id_photo5">Photo5:</label>
            {{ form.photo5 }}
        </div>
        <div class="field">
            {{ form.photo6.errors }}
            <label for="id_photo6">Photo6:</label>
            {{ form.photo6 }}
        </div>
        <div class="field">
            {{ form.message.errors }}
            <label for="id_message">Concept:</label>
            {{ form.message }}
        </div>
       
        
        
        <input type="submit" value="Submit">
    </form>
{% endblock %}

CodiPlatform/templates/setting_codi_sidebar.html
{% extends "sidebar.html" %}

{% block sidebar %}
<h2><font color="white">Codi Setting</font></h2>
<table width = "100%" border = "0" bordercolor = "black">
<tr><td><a href="/setting/codi/push_album/">Add Albums</a></td></tr>

</table>
{% endblock %}

CodiPlatform/templates/showcase_vote.html
{% extends "nosidebar.html" %}

{% block main %}
<h1> Showcase </h1>

	<table>
	<tr>
	<td width = "50%">
	
	<table>
	<tr><td><h2>{{album1.title}}</h2></td></tr>
	<tr>
	{% for photo in photos1 %}
			{% if forloop.counter0|divisibleby:"3" %}
			{% if forloop.counter0 != 0 %}
			</tr><tr>
			{% endif %}
		{% endif %}
	
		<td>
		<a href = "/album/{{album1.album_id}}"><img src="{{ MEDIA_URL }}photos/{{photo.photo_id}}"  width = 150 height = 200/></a>
		</td>
		
	{% endfor %}
	</tr>
	<tr><td>
	<p><h3>{{album1.message}}</h3></p>
	</td></tr>	
	</table>
	
	</td>
	<td width = "50%">
	
	<table>
	<tr><td><h2>{{album2.title}}</h2></td></tr>
	<tr>
	{% for photo in photos2 %}
			{% if forloop.counter0|divisibleby:"3" %}
			{% if forloop.counter0 != 0 %}
			</tr><tr>
			{% endif %}
		{% endif %}
	
		<td>
		<img src="{{ MEDIA_URL }}photos/{{photo.photo_id}}"  width = 150 height = 200/>
		</td>
		
	{% endfor %}
	</tr>
	<tr><td>
	<p><h3>{{album2.message}}</h3></p>
	</td></tr>	
	</table>
	
	</tr>
	</td>
	</table>

{% endblock %}

CodiPlatform/templates/sidebar.html
{% extends "base.html" %}
{% block content %}
<div id="left" onMouseOver="document.all.dropdown.style.display = 'none'">
	{% block sidebar %}{% endblock %}
</div>
    
<div id="mainouter" onMouseOver="document.all.dropdown.style.display = 'none'">
	{% block sidemain %}{% endblock %}
</div>
    	
{% endblock %}

CodiPlatform/templates/test_setting_codi_push_album.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Untitled Document</title>
</head>

<body>
<input type="hidden" name="MAX_FILE_SIZE" value="500" />
<input type="file" name="Upload file1" />

</body>
</html>

CodiPlatform/templates/tryout.html
{% extends "nosidebar.html" %}

{% block main %}
<h1> Try Out </h1>
{% endblock %}